### ISSUE TITLE
gitsh crashes when referencing $_prior does not exist

### ISSUE THREAD

**Issue by bernerdschaefer** [thoughtbot/gitsh#230] opened 2015-06-30 00:12 UTC
Here's the sequence of commands I performed to encounter the error:

```
> gitsh
checkout -b feature-branch
checkout master
branch -d $_prior
branch -d $_prior
```

And here's a simplified case:

```
> gitsh
!echo $_prior
```

### What happened

gitsh printed the following message and exited:

```
gitsh: Error: no implicit conversion of nil into String
```

### What I expected to happen

I expected gitsh to do one of the following, and continue accepting commands:

- print error about the variable not existing
- run the command with an empty value, and let errors bubble up

**Comment by bernerdschaefer** [comment] 2015-06-30 00:14
On this error, gitsh exited with a 0 status code. Would a separate issue for that be helpful?

**Comment by georgebrock** [comment] 2015-07-31 18:57
@bernerdschaefer Both good catches, thanks!

**Comment by georgebrock** [comment] 2015-08-07 18:06
Full stack trace from running this against the development version (`bin/gitsh` in this repo):

```
tmp master@ branch -d $_prior
/Users/georgebrocklehurst/code/gitsh/lib/gitsh/shell_command_runner.rb:13:in `spawn': no implicit conversion of nil into String (TypeError)
        from /Users/georgebrocklehurst/code/gitsh/lib/gitsh/shell_command_runner.rb:13:in `run'
        from /Users/georgebrocklehurst/code/gitsh/lib/gitsh/shell_command_runner.rb:4:in `run'
        from /Users/georgebrocklehurst/code/gitsh/lib/gitsh/commands/git_command.rb:18:in `execute'
        from /Users/georgebrocklehurst/code/gitsh/lib/gitsh/commands/error_handler.rb:10:in `execute'
        from /Users/georgebrocklehurst/code/gitsh/lib/gitsh/interpreter.rb:12:in `execute'
        from /Users/georgebrocklehurst/code/gitsh/lib/gitsh/interactive_runner.rb:75:in `interactive_loop'
        from /Users/georgebrocklehurst/code/gitsh/lib/gitsh/interactive_runner.rb:30:in `run'
        from /Users/georgebrocklehurst/code/gitsh/lib/gitsh/cli.rb:30:in `run'
        from ./bin/gitsh:12:in `<main>'
```

The development version's exit status was 1, which suggests the incorrect exit status is a problem with the C wrapper.

**Comment by georgebrock** [comment] 2015-08-07 18:20
Looks like the root cause of this problem is that the `Gitsh::MagicVariables` class returns `nil` for things that don't have a value. Since ce6ac1b3 we've considered unset non-magic variables to be an error, and we raise a `Gitsh::UnsetVariableError` when we encounter them. We should probably solve this by doing the same thing with magic variables.

**Comment by georgebrock** [comment] 2015-09-03 14:32
Closing in favour of #237

**Closed by georgebrock** 2015-09-03 14:32 UTC
Labels: bug
