### ISSUE TITLE
readline problems

### ISSUE THREAD

**Issue by jjb** [thoughtbot/gitsh#281] opened 2017-01-31 21:38 UTC
rl_completion_suppress_quote is (erroneously?) not found. No matter what I point ./configure at, it never finds `rl_completion_suppress_quote`, introduced in readline 5 (https://cnswww.cns.cwru.edu/php/chet/readline/CHANGES). I've hand-verified that the readline that it's pointing at has this variable. if i comment out the `readline.require_func` checks, configure succeeds, but make does indeed break.

if i download readline and build it and point gitsh at it, it fails

```
➔ CPPFLAGS="-I/Users/john/tmp/build/usr/local/include/readline/" LDFLAGS="-L/Users/john/tmp/build/usr/local/lib/" ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for ruby... /usr/bin/ruby
checking for ruby... (cached) /usr/bin/ruby
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for ruby version... ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
checking for tgetnum() in -lncurses... yes
checking for readline/readline.h... yes
checking for readline/history.h... yes
checking for readline() in -lreadline... no
extconf.rb:51:in `<main>': readline not found (RuntimeError)
configure: error: Failed to configure Ruby extension
```

i can't use `--with-readline-dir` 

> configure: WARNING: unrecognized options: --with-readline-dir

even though the error output of ./configure says i can...

```
Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
	--with-curses-dir
	--without-curses-dir
	--with-curses-include
	--without-curses-include=${curses-dir}/include
	--with-curses-lib
	--without-curses-lib=${curses-dir}/
	--with-ncurses-dir
	--without-ncurses-dir
	--with-ncurses-include
	--without-ncurses-include=${ncurses-dir}/include
	--with-ncurses-lib
	--without-ncurses-lib=${ncurses-dir}/
	--with-termcap-dir
	--without-termcap-dir
	--with-termcap-include
	--without-termcap-include=${termcap-dir}/include
	--with-termcap-lib
	--without-termcap-lib=${termcap-dir}/
	--with-readline-dir
	--without-readline-dir
	--with-readline-include
	--without-readline-include=${readline-dir}/include
	--with-readline-lib
	--without-readline-lib=${readline-dir}/
	--with-ncurseslib
	--without-ncurseslib
	--with-readlinelib
	--without-readlinelib
```

please advise. thanks!

**Comment by jjb** [comment] 2017-01-31 21:52
`have_library("readline", "readline")` is false

**Comment by jjb** [comment] 2017-02-01 00:45
the above was with default ruby on macos sierra

now i've installed ruby 2.4 with macport and pointed the config script to it, and it worked

`RUBY=$(which ruby) ./configure`

no library dir config needed

because macports ruby has readline properly built in?

anyway, would be nice for it to work with default ruby. lmk if you want me to experiment more on my machine or want more info.

**Comment by jjb** [comment] 2017-02-01 00:51
https://gist.github.com/jjb/45c129380e2f344df19b618e1f0075b9

**Comment by georgebrock** [comment] 2017-02-01 14:56
Thanks for the detailed error report, @jjb. I've not had trouble using default macOS system Ruby or heard of similar problems, but I've personally only tested on El Cap so far.

@mike-burns This sounds like it might be a little similar to the problems you had packaging for OpenBSD. Do you think the patch you applied there is likely to help with this issue too?

**Comment by mike-burns** [comment] 2017-02-01 15:02
Yes that is exactly the issue I ran into on OpenBSD.

My diff is not in the ports tree yet (on my todo list) but the patch is here: https://marc.info/?l=openbsd-ports&m=148340820830595&w=2

In `configure` around line 3763 the patch passes `--with-readline-include`, `--with-readline-lib`, and `--with-readlinelib` to `extconf.rb`.

**Comment by jakeboxer** [comment] 2017-03-20 19:01
I'm seeing this same error on a brand new Mac:

```
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/gitsh/0.11.1
Last 15 lines from /Users/jakecard/Library/Logs/Homebrew/gitsh/01.configure:
	--without-termcap-include=${termcap-dir}/include
	--with-termcap-lib
	--without-termcap-lib=${termcap-dir}/
	--with-readline-dir
	--without-readline-dir
	--with-readline-include
	--without-readline-include=${readline-dir}/include
	--with-readline-lib
	--without-readline-lib=${readline-dir}/
	--with-ncurseslib
	--without-ncurseslib
	--with-readlinelib
	--without-readlinelib
extconf.rb:51:in `<main>': readline not found (RuntimeError)
configure: error: Failed to configure Ruby extension
```

What steps should I take to fix this?

**Comment by jjb** [comment] 2017-03-20 19:19
@jakeboxer my gist above might be helpful

**Comment by jakeboxer** [comment] 2017-03-20 21:11
@jjb appreciate it! This is a work computer and I want to avoid tacking on things like MacPorts and other versions of Ruby, so for now I think I'll hold off for a fix, but I'll probably use that on my personal computer. Thanks!

**Comment by joesasson** [comment] 2017-03-20 22:51
@jjb @jakeboxer I just had an identical error when trying to install with homebrew. The steps in the gist fixed it, but it only works if you run the commands from inside a cloned repo of the project. 

So I would just add to the beginning of the gist:
```
git clone git@github.com:thoughtbot/gitsh.git
cd gitsh
.
.
.
```
I'm not sure if this was obvious, just putting it our there, because at first I was just trying to run the commands from a random directory. 

Thanks for the gist @jjb!

**Comment by jjb** [comment] 2017-03-21 00:54
@joesasson updated, thanks!

**Comment by georgebrock** [comment] 2017-03-22 15:00
@jakeboxer There are some instructions in the `INSTALL` file for non-homebrew installs of gitsh with homebrew Readline:

https://github.com/thoughtbot/gitsh/blob/master/INSTALL#L52-L54

Does that help at all?

**Comment by jakeboxer** [comment] 2017-03-22 18:57
@georgebrock oh sorry, I'm doing a homebrew install on both my work and personal computers, I just want to avoid adding in MacPorts and installing extra versions of Ruby and readline on my work computer :smile:

**Comment by georgebrock** [comment] 2017-03-22 20:50
You'll definitely need to install Readline—as far as I'm aware macOS only ships with libedit, which gitsh no longer supports—but you shouldn't need an additional Ruby.

**Comment by philippec** [comment] 2017-03-29 18:24
How does one install Readline _without_ installing MacPorts, Homebrew, or some other package manager? Is there a tarball that one can configure/make/sudo make install to be on our way?

**Comment by jjb** [comment] 2017-03-29 18:27
@philippec i think you won't have a good experience trying to install it from source. even the gnu people don't give clear instructions how https://cnswww.cns.cwru.edu/php/chet/readline/rltop.html#Distributions

**Comment by philippec** [comment] 2017-03-31 03:00
@jjb that's unfortunate. It means that I have to keep on using v0.10 for now until it breaks.

FWIW I downloaded the source and configure/make/sudo make install and that *seemed* to work, but then doing the same on gitsh did not build "out of the box" like previous versions did.

I respect the choice that the authors made to require Readline, and I realize that it probably can't be bundled in the install, but I find it a pity that it now has an external dependency.

**Comment by georgebrock** [comment] 2017-03-31 13:57
It is possible to install Readline from source: `./configure && make && make install` worked fine for me on macOS Sierra with the latest tarball from https://ftp.gnu.org/gnu/readline/

Configuring gitsh to find Readline in a specific non-standard directory is more tricky, which is why using Homebrew is pretty helpful right now. We should be able to support some additional options in the gitsh `configure` script to make this easier.

**Comment by georgebrock** [comment] 2017-04-03 01:58
@jjb @philippec Here are the commands I used to build and install Readline and gitsh from source. There are two tricks to making this work:

1. Building Readline as a macOS universal binary, because that's how system Ruby on macOS builds C extensions, so it needs multiple architectures to link properly.
2. Making sure gitsh finds your version of Readline.

I was trying this out, so I was using a prefix under my home directory as a sandbox. If you want to use this for a real installation, I suggest modifying everything that refers to `$HOME/gitsh-test` to something more sensible, like `/usr/local`. You may also need to use `sudo` for the various `make install` commands.

```sh
# Get Readline
curl -O https://ftp.gnu.org/gnu/readline/readline-7.0.tar.gz
tar -zxf readline-7.0.tar.gz
cd readline-7.0

# Build Readline
env CFLAGS="-arch x86_64 -arch i386" LDFLAGS="-arch x86_64 -arch i386" \
    ./configure --prefix="$HOME/gitsh-test/"
make
make install
cd ..

## Get gitsh
curl -OL https://github.com/thoughtbot/gitsh/releases/download/v0.11.1/gitsh-0.11.1.tar.gz
tar -zxf gitsh-0.11.1.tar.gz
cd gitsh-0.11.1

# Build gitsh
env CPPFLAGS="-I$HOME/gitsh-test/include" LDFLAGS="-L$HOME/gitsh-test/lib" \
    ./configure --prefix="$HOME/gitsh-test"
make
make install
cd ..

# Test the installed version is working
$HOME/gitsh-test/bin/gitsh
```

**Comment by georgebrock** [comment] 2017-04-03 02:40
Given that

- it is possible to install from source on macOS,
- I've written down how to make that work,
- we recommend installing via Homebrew, and
- I've opened #284 to fix the more complex OpenBSD case,

I'm going to close this. Please re-open if you have further problems.

**Closed by georgebrock** 2017-04-03 02:40 UTC

**Comment by jjb** [comment] 2017-12-12 19:47
Some more followup in case folks find this thread in the future

I was just running into this problem yet again, even when using [my gist recipe](https://gist.github.com/jjb/45c129380e2f344df19b618e1f0075b9).

Then I realized that even though I had done `sudo port select ruby ruby24`, because I hadn't opened a new Terminal window, I was still on the OS ruby with the old readline version.

I've now updated the gist to reflect this, and all is well again.

I don't know if / how much this problem was causing the problems I described in my original post above... 🤦‍♂️

**Comment by paxperscientiam** [comment] 2018-01-02 06:20
@jjb I can confirm that `configure` works after installing `ruby24`. 
`RUBY=/opt/local/bin/ruby2.4 ./configure`


I tried getting it to work with the readline library that had been installed by macports, but no such luck.

**Comment by jjb** [comment] 2018-03-29 05:06
gist still works for ruby 2.5

https://gist.github.com/jjb/45c129380e2f344df19b618e1f0075b9

**Comment by jjb** [comment] 2019-04-17 18:28
still works for macOS 10.14 and gitsh 0.14

**Comment by jjb** [comment] 2023-05-28 00:40
still works for macOS 13, gitsh 0.14, ruby 3.2
