### ISSUE TITLE
Commands that are too long write over the command prompt

### ISSUE THREAD

**Issue by rmeritz** [thoughtbot/gitsh#144] opened 2014-03-17 09:41 UTC
They should probably instead go to the next line.

![screenshot from 2014-03-17 10 37 35](https://f.cloud.github.com/assets/352375/2434674/f31d0018-adb7-11e3-80ea-140c160352f3.png)

I'm using a Bash Shell on a Debian Machine.

**Comment by georgebrock** [comment] 2015-01-10 15:37
I've finally figured out how to reliably reproduce this issue. Unfortunately, #160 didn't fix it.

1. Start `gitsh` in a small terminal emulator window.
2. Run a command that launches a pager or some other curses interface, e.g. `log` or `!less somefile.txt` or `!vim`.
3. Resize the terminal emulator window while the pager (etc.) is running.
4. Quit the pager.
5. Type a long command: it will wrap without adding a new line and overwrite the prompt.
6. Resize the terminal emulator window again.
7. Continue typing: the wrapping will be fixed.

**Comment by georgebrock** [comment] 2015-01-20 22:32
I think I have a solution to this: it looks like `Readline.readline` sets `ENV['COLUMNS']`, and `tput cols` will read `ENV['COLUMNS']`, so we're just telling Readline something that it already knows.

`stty size` seems to produce more reliable output, ignoring the environment variable.

**Comment by georgebrock** [comment] 2015-01-20 23:06
An stty(1) based fix for this is work-in-progress on the branch `gb-window-resize`

**Comment by mike-burns** [comment] 2015-01-21 12:18
This is the GNU implementation: http://git.savannah.gnu.org/cgit/coreutils.git/tree/src/stty.c#n1586
This is the Apple: http://www.opensource.apple.com/source/adv_cmds/adv_cmds-149/stty/stty.c

Most BSDs look identical to the Apple one.

GNU falls back to `$COLUMNS` on systems that don't have `TIOCGWINSZ`, but there should be none of those. Linux documents theirs in ioctl_list(2) and OpenBSD in tty(4).

You could call `IO.ioctl` directly from Ruby! Or just stick with shelling out to stty(1).

**Comment by georgebrock** [comment] 2015-01-21 15:41
@mike-burns After experimenting with `IO.ioctl`, I think it's going to be tricky to make it work across platforms without direct access to the constants in `sys/ioctl.h`, which Ruby doesn't expose.

That said, POSIX requires both [stty][posix_stty] and [tput][posix_tput], but not the `size` and `lines`/`cols` arguments we're using here, and anecdotally, [`stty size` doesn't work on Solaris][solaris].

It seems like the best bet would be to try these commands in order:

1. `stty size`
2. `env COLUMNS='' tput cols` and `env LINES='' tput lines`
3. `tput cols` and `tput lines`

[posix_stty]: http://pubs.opengroup.org/onlinepubs/9699919799/utilities/stty.html
[posix_tput]: http://pubs.opengroup.org/onlinepubs/009695399/utilities/tput.html
[solaris]: https://nixshell.wordpress.com/2009/09/08/get-the-width-of-the-terminal/#comment-5301

**Closed** 2015-01-26 22:27 UTC
Labels: bug
